import type { NextPageContext } from 'next'
import Head from 'next/head'
import React from 'react';
import {ParsedUrlQuery} from 'querystring'
import {Container, Row, Col,Button} from 'react-bootstrap';
//import Icon, { FontAwesome, Feather } from 'react-web-vector-icons';
// index.html

type TProps ={
  title?:string
}
const Header=(props:TProps)=> {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
     
      <h1>{props.title ? props.title : 'Default title'}</h1>
    </>
  );
}

interface IProps {
  userAgent?: string;
  query?:ParsedUrlQuery
}

interface IState {
  likes:number
}
export class HomePage extends React.Component<IProps,IState> {
  names = ['Ada Lovelace', 'Grace Hopper', 'Margaret Hamilton'];
  
  static async getInitialProps({ req,query}: NextPageContext) {
    
    const userAgent = req ? req.headers['user-agent'] : navigator.userAgent
    console.log(req)
    return {  userAgent,query}
  }
  constructor(props:IProps) {
    super(props)
  
    this.state = {
      likes:0
    }
  }


  handleClick=()=> {
    const {likes}=this.state
    this.setState({likes:likes + 1});
  }

  render() {
    const {likes} =this.state
    console.log("userAgent",this.props.userAgent)
    console.log("query",this.props.query)
    
    return (
            <>
            <Header title="Develop. Preview. Ship. 🚀" />
            <Container fluid>
              
              
                
                {this.names.map((name) => (
                  <Row key={name}>{name}</Row>
                ))}
              
              

              <Button onClick={this.handleClick}>Like {likes}</Button>
            </Container>
            </>
            
          )
  }
}

export default HomePage